//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoveleenEf_project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoveleenBookDetail
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Category { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> Edition { get; set; }
        public string BookCondition { get; set; }
        public Nullable<bool> Available { get; set; }
    }
}
